export const TASTE_PREFERENCES = [
  "Savory",
  "Sweet",
  "Spicy",
  "Umami-rich",
  "Smoky",
  "Tangy",
  "Rich & creamy",
  "Crispy & crunchy",
  "Fresh & light",
  "Herby",
  "Garlicky",
  "Nutty",
  "Buttery",
  "Bold & intense",
  "Mild",
  "Comfort food",
  "Fermented & funky",
  "Charred & grilled",
  "Citrusy",
  "Earthy",
] as const;

export const COMMON_ALLERGENS = [
  "Peanuts",
  "Tree nuts",
  "Milk/Dairy",
  "Eggs",
  "Wheat",
  "Gluten",
  "Soy",
  "Fish",
  "Shellfish",
  "Sesame",
] as const;

export const REGIONAL_CUISINES = [
  "Argentinian",
  "Brazilian",
  "British",
  "Cajun & Creole",
  "Caribbean",
  "Chinese",
  "Colombian",
  "Cuban",
  "Ecuadorian",
  "Ethiopian",
  "Filipino",
  "French",
  "German",
  "Greek",
  "Indian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Lebanese",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Moroccan",
  "Pakistani",
  "Peruvian",
  "Puerto Rican",
  "Southern (US)",
  "Spanish",
  "Tex-Mex",
  "Thai",
  "Turkish",
  "Vietnamese",
] as const;

export const APPLIANCES = [
  "Oven",
  "Stovetop",
  "Grill",
  "Air fryer",
  "Instant Pot / pressure cooker",
  "Slow cooker",
  "Dutch oven",
  "Cast iron skillet",
  "Wok",
  "Stand mixer",
  "Food processor",
  "Blender",
  "Sous vide",
  "Rice cooker",
  "Griddle",
  "Smoker",
] as const;

export const PANTRY_STAPLES = [
  "Rice",
  "Pasta",
  "Potatoes",
  "Onions",
  "Garlic",
  "Carrots",
  "Celery",
  "Bell peppers",
  "Ground beef",
  "Chicken breast",
  "Chicken thighs",
  "Eggs",
  "Milk",
  "Butter",
  "Olive oil",
  "Flour",
  "Sugar",
  "Salt",
  "Black pepper",
  "Canned tomatoes",
  "Chicken stock",
  "Soy sauce",
  "Bread",
] as const;
