export const TASTE_PREFERENCES = [
  "Savory",
  "Sweet",
  "Spicy",
  "Umami-rich",
  "Smoky",
  "Tangy",
  "Rich & creamy",
  "Crispy & crunchy",
  "Fresh & light",
  "Herby",
  "Garlicky",
  "Nutty",
  "Buttery",
  "Bold & intense",
  "Mild",
  "Comfort food",
  "Fermented & funky",
  "Charred & grilled",
  "Citrusy",
  "Earthy",
] as const;

export const COMMON_ALLERGENS = [
  "Peanuts",
  "Tree nuts",
  "Milk/Dairy",
  "Eggs",
  "Wheat",
  "Gluten",
  "Soy",
  "Fish",
  "Shellfish",
  "Sesame",
] as const;

// Roughly ordered by how commonly people actually cook/order it, most to
// least -- not alphabetical -- since this order drives what shows up first
// when browsing with no search text typed yet.
export const REGIONAL_CUISINES = [
  "Italian",
  "Mexican",
  "Chinese",
  "Japanese",
  "Thai",
  "Indian",
  "French",
  "Mediterranean",
  "Greek",
  "Korean",
  "Vietnamese",
  "Spanish",
  "Middle Eastern",
  "Southern (US)",
  "Cajun & Creole",
  "Tex-Mex",
  "Caribbean",
  "Lebanese",
  "Moroccan",
  "Turkish",
  "Filipino",
  "Indonesian",
  "Ethiopian",
  "Peruvian",
  "Brazilian",
  "Argentinian",
  "Colombian",
  "Cuban",
  "Puerto Rican",
  "Ecuadorian",
  "Pakistani",
  "German",
  "British",
] as const;

export const APPLIANCES = [
  "Oven",
  "Stovetop",
  "Grill",
  "Air fryer",
  "Instant Pot / pressure cooker",
  "Slow cooker",
  "Dutch oven",
  "Cast iron skillet",
  "Wok",
  "Stand mixer",
  "Food processor",
  "Blender",
  "Sous vide",
  "Rice cooker",
  "Griddle",
  "Smoker",
] as const;

export const PANTRY_STAPLES = [
  "Rice",
  "Pasta",
  "Potatoes",
  "Onions",
  "Garlic",
  "Carrots",
  "Celery",
  "Bell peppers",
  "Ground beef",
  "Chicken breast",
  "Chicken thighs",
  "Eggs",
  "Milk",
  "Butter",
  "Olive oil",
  "Flour",
  "Sugar",
  "Salt",
  "Black pepper",
  "Canned tomatoes",
  "Chicken stock",
  "Soy sauce",
  "Bread",
] as const;

// Broad enough to narrow down against as someone types an ingredient name,
// independent of what's specifically marked as a pantry staple.
export const COMMON_INGREDIENTS = [
  // Proteins
  "Chicken breast",
  "Chicken thighs",
  "Chicken wings",
  "Ground beef",
  "Ground turkey",
  "Ground pork",
  "Steak",
  "Pork chops",
  "Pork shoulder",
  "Bacon",
  "Sausage",
  "Ham",
  "Shrimp",
  "Salmon",
  "White fish",
  "Tuna",
  "Tofu",
  "Eggs",
  "Black beans",
  "Chickpeas",
  "Kidney beans",
  "Lentils",
  // Vegetables
  "Onions",
  "Garlic",
  "Ginger",
  "Carrots",
  "Celery",
  "Bell peppers",
  "Jalapeños",
  "Tomatoes",
  "Canned tomatoes",
  "Tomato paste",
  "Potatoes",
  "Sweet potatoes",
  "Broccoli",
  "Cauliflower",
  "Spinach",
  "Kale",
  "Lettuce",
  "Cabbage",
  "Zucchini",
  "Mushrooms",
  "Corn",
  "Green beans",
  "Peas",
  "Cucumber",
  "Avocado",
  "Scallions",
  // Fruit
  "Lemon",
  "Lime",
  "Orange",
  "Apple",
  "Banana",
  "Pineapple",
  "Mango",
  // Dairy
  "Milk",
  "Butter",
  "Heavy cream",
  "Sour cream",
  "Yogurt",
  "Cheddar cheese",
  "Mozzarella",
  "Parmesan",
  "Cream cheese",
  // Grains & starches
  "Rice",
  "Pasta",
  "Bread",
  "Tortillas",
  "Quinoa",
  "Oats",
  "Flour",
  // Pantry & condiments
  "Olive oil",
  "Vegetable oil",
  "Butter",
  "Salt",
  "Black pepper",
  "Sugar",
  "Brown sugar",
  "Honey",
  "Soy sauce",
  "Fish sauce",
  "Oyster sauce",
  "Vinegar",
  "Chicken stock",
  "Beef stock",
  "Vegetable stock",
  "Coconut milk",
  "Mayonnaise",
  "Mustard",
  "Ketchup",
  "Hot sauce",
  "Salsa",
  "Peanut butter",
  "Breadcrumbs",
  // Herbs & spices
  "Basil",
  "Cilantro",
  "Parsley",
  "Thyme",
  "Rosemary",
  "Oregano",
  "Cumin",
  "Paprika",
  "Chili powder",
  "Cinnamon",
  "Curry powder",
  "Red pepper flakes",
  "Bay leaves",
] as const;
